services:
  msvc-configserver:
    container_name: spring-config
    image: msvc-configserver:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud
  eureka-server:
    container_name: eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  mysql:
    container_name: mysql-container
    image: mysql:8.0.42
    ports:
      - "3307:3306"
    restart: always
    networks:
      - springcloud
    environment:
      - MYSQL_DATABASE=msvc_products_db
      - MYSQL_ROOT_PASSWORD=38216639
  zipkin-server:
    container_name: zipkin-server
    image: zipkin-server
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
  msvc-products:
    container_name: msvc-products
    image: msvc-products
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql
      - eureka-server
      - zipkin-server
  msvc-items:
    container_name: msvc-items
    image: msvc-items
    ports:
      - "8020:8020"
      - "8005:8005"
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - zipkin-server
      - msvc-products
  msvc-users:
    container_name: msvc-users
    image: msvc-users
    restart: always
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - zipkin-server
      - mysql
  msvc-oauth:
    container_name: msvc-oauth
    image: msvc-oauth
    restart: always
    ports:
      - "9100:9100"
    networks:
      - springcloud
    depends_on:
      - eureka-server
      - zipkin-server
      - msvc-users
  msvc-gateway-server:
    container_name: msvc-gateway-server
    image: msvc-gateway-server
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springcloud
    environment:
      - IP_ADDR=http://192.168.1.40:9100
    depends_on:
      - eureka-server
      - zipkin-server
      - msvc-products
      - msvc-items
      - msvc-users
      - msvc-oauth
networks:
  springcloud: