config:
  baseurl:
    endpoint:
      msvc-products: lb://msvc-products

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        #configuramos las llamadas lentas
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: default
  #configuramos el TimeOut
  timelimiter:
    configs:
      default:
        timeout-duration: 3s #cambiarlo a 4 si queremos menajer las llamadas lentas
    instances:
      items:
        base-config: default
